#!/usr/bin/env bash
set -euo pipefail

CLUSTER_NAME="$1"

# Grab the cluster kubeconfig.
export KUBECONFIG="tmp/${CLUSTER_NAME}-kubeconfig.yaml"

# Delete the example Helm installation.
helm delete --purge istio || true
kubectl delete psp -l "release=istio" -A || true