#!/usr/bin/env bash
set -euo pipefail

CLUSTER_NAME="$1"

# Grab the cluster kubeconfig.
export KUBECONFIG="tmp/${CLUSTER_NAME}-kubeconfig.yaml"

# Delete the example namespaces.
kubectl delete namespace istio-system

# Delete the example Helm installation.
kubectl delete --purge istio || true