#!/usr/bin/env bash
set -euo pipefail

# Grab the cluster name with a default of "istio-demo".
CLUSTER_NAME=${1:-istio-demo}

# Run the clean script on down so associated LBs and volumes are deleted first.
script/clean ${CLUSTER_NAME}

# Delete the cluster.
../script/delete-cluster ${CLUSTER_NAME}