#!/usr/bin/env bash
DEBUG=${DEBUG:-}
if [ ! -z "${DEBUG}" ]; then
    set -x
fi
set -euo pipefail
mkdir -p tmp

# Grab the cluster name with a default of "metrics-demo".
CLUSTER_NAME=${1:-metrics-demo}

# Create the cluster or use the existing.
../script/create-cluster ${CLUSTER_NAME}

# Grab the cluster kubeconfig.
export KUBECONFIG="tmp/${CLUSTER_NAME}-kubeconfig.yaml"

# Install Helm/tiller and wait for it to be Ready.
(
    cd ../helm
    script/up ${CLUSTER_NAME}
)

# Install metrics-server
NAMESPACE="metrics"
echo "Install metrics-server via Helm"
helm upgrade metrics-server --install --namespace ${NAMESPACE} -f ../metrics-server/values.yaml stable/metrics-server
echo "Waiting for pods to be Ready"
kubectl wait --for=condition=Ready pods -l "release=metrics-server" -n ${NAMESPACE} --timeout=120s
echo "🎉"
