#!/usr/bin/env bash
DEBUG=${DEBUG:-}
if [ ! -z "${DEBUG}" ]; then
    set -x
fi
if [ -z "${1}" ]; then
    echo "usage: cluster-kubeconfig <cluster-name>"
    exit 1
fi
set -euo pipefail

NAME="${1}"

# Grab the cluster kubeconfig.
mkdir -p tmp
doctl k8s cluster kubeconfig show ${NAME} > tmp/${NAME}-kubeconfig.yaml
echo "$(pwd)/tmp/${NAME}-kubeconfig.yaml"
