#!/usr/bin/env bash
DEBUG=${DEBUG:-}
if [ ! -z "${DEBUG}" ]; then
    set -x
fi
if [ -z "${1}" ]; then
    echo "usage: create-cluster <cluster-name>"
    exit 1
fi
set -euo pipefail

NAME="${1}"
REGION="${REGION:-sfo2}"
NODE_SIZE="${NODE_SIZE:-s-1vcpu-2gb}"
NODE_COUNT="${NODE_COUNT:-2}"
DEFAULT_VERSION="$(doctl k8s options versions -ojson | jq --raw-output 'first(.[] | select(.slug | test("^1.14.[0-9]+-do.[0-9]+$")) | .slug)')"
VERSION="${CLUSTER_VERSION:-${DEFAULT_VERSION}}"

# Retries a command on failure.
# $1 - the max number of attempts
# $2... - the command to run
retry() {
    local -r -i max_attempts="$1"; shift
    local -r cmd="$@"
    local -i attempt_num=1

    until $cmd
    do
        if (( attempt_num == max_attempts ))
        then
            echo "Attempt $attempt_num failed and there are no more attempts left!"
            return 1
        else
            echo "Attempt $attempt_num failed! Trying again in $attempt_num seconds..."
            sleep $(( attempt_num++ ))
        fi
    done
}

export KUBECONFIG="$(pwd)/tmp/${NAME}-kubeconfig.yaml"

function save_kubeconfig() {
    mkdir -p tmp
    if [ ! -f ${KUBECONFIG} ]; then
        doctl k8s cluster kubeconfig show ${1} > ${KUBECONFIG}
    else
        SERVER="$(cat ${KUBECONFIG} | grep "server:" | awk '{$1=$1};1' | cut -d ' ' -f 2 || true)"
        echo "Cluster API: ${SERVER}"
        if ! curl -k ${SERVER} &> /dev/null; then
            echo "${KUBECONFIG} exists already but is not reachable, grabbing it again"
            doctl k8s cluster kubeconfig show ${1} > ${KUBECONFIG}
        else
            echo "${KUBECONFIG} exists already, using it"
        fi
    fi
    echo "KUBECONFIG=${KUBECONFIG}"
}

# Check for existence of the cluster and create if necessary.
echo "Cluster: ${NAME}"
if retry 10 doctl k8s cluster get ${NAME} &> /dev/null; then
    echo "Cluster ${NAME} exists already, using it"
    save_kubeconfig ${NAME}
else
    # Create the cluster.
    echo "Creating cluster ${NAME} on ${VERSION}"
    doctl k8s cluster create ${NAME} \
        --region ${REGION} \
        --node-pool "name=${NAME};size=${NODE_SIZE};count=${NODE_COUNT}" \
        --version ${VERSION} \
        --update-kubeconfig=false

    # Grab the cluster kubeconfig.
    save_kubeconfig ${NAME}

    # Wait for all the nodes to be Ready.
    echo "Waiting for nodes to be up and Ready"
    while ! kubectl get nodes; do
        sleep 5
    done
    while [ "$(kubectl get nodes --no-headers | wc -l | tr -d '[:space:]')" != "${NODE_COUNT}" ]; do
        sleep 5
    done
    kubectl wait --for=condition=Ready nodes --all --timeout=300s
fi
