#!/usr/bin/env bash
DEBUG=${DEBUG:-}
if [ ! -z "${DEBUG}" ]; then
    set -x
fi
if [ -z "${1}" ]; then
    echo "usage: create-cluster <cluster-name>"
    exit 1
fi
set -euo pipefail

NAME="${1}"
REGION="${REGION:-sfo2}"
NODE_SIZE="${NODE_SIZE:-s-1vcpu-2gb}"
NODE_COUNT="${NODE_COUNT:-2}"
VERSION="${CLUSTER_VERSION:-1.14.2-do.0}"

function save_kubeconfig() {
    mkdir -p tmp
    doctl k8s cluster kubeconfig show ${1} > tmp/${1}-kubeconfig.yaml
    echo "KUBECONFIG=$(pwd)/tmp/${1}-kubeconfig.yaml"
}

# Check for existence of the cluster and create if necessary.
if doctl k8s cluster get ${NAME} > /dev/null 2>&1; then
    echo "Cluster ${NAME} exists already, using it"
    save_kubeconfig $NAME
else
    # Create the cluster.
    echo "Creating cluster ${NAME}"
    doctl k8s cluster create ${NAME} \
        --region ${REGION} \
        --node-pool "name=${NAME};size=${NODE_SIZE};count=${NODE_COUNT}" \
        --version ${VERSION} \
        --update-kubeconfig=false

    # Grab the cluster kubeconfig.
    mkdir -p tmp
    doctl k8s cluster kubeconfig show ${NAME} > tmp/${NAME}-kubeconfig.yaml
    export KUBECONFIG="$(pwd)/tmp/${NAME}-kubeconfig.yaml"
    echo "KUBECONFIG=${KUBECONFIG}"

    # Wait for all the nodes to be Ready.
    echo "Waiting for nodes to be up and Ready"
    while ! kubectl get nodes; do
        sleep 5
    done
    while [ "$(kubectl get nodes | wc -l | tr -d '[:space:]')" == "0" ]; do
        sleep 5
    done
    kubectl wait --for=condition=Ready nodes --all --timeout=300s
fi
