#!/usr/bin/env bash
set -euo pipefail
EXTERNAL_IP=""
SERVICE="$1"
NAMESPACE="$2"
while [ -z $EXTERNAL_IP ]; do
  EXTERNAL_IP=$(kubectl get service ${SERVICE} -n ${NAMESPACE} --template="{{range .status.loadBalancer.ingress}}{{.ip}}{{end}}")
  if [ -z "${EXTERNAL_IP}" ]; then
    echo "Waiting for LoadBalancer service IP..."
    sleep 10
  fi
done
echo "Ready: ${EXTERNAL_IP}"
